default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_express_development

test:
  <<: *default
  database: food_express_test

production:
  <<: *default
  database: food_express_production
  username: food_express
  password: <%= ENV["FOOD_EXPRESS_DATABASE_PASSWORD"] %>
